server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
